services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev

    env_file:
      - ./.env

    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
