name: Build

on:
  push:
    branches: [master]

  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit dependencies
        run: pnpm dlx audit-ci@^7 --config ./.audit-ci.jsonc

      - name: Run tests
        run: pnpm run --if-present test

      - name: Lint
        run: pnpm run lint

      - name: Check types
        run: pnpm run typecheck

      - name: Build the app
        run: pnpm run build

      - uses: twingate/github-action@v1.5
        if: github.event_name == 'push' && github.ref_name == 'master'
        with:
          service-key: ${{ secrets.SERVICE_KEY }}

      - name: Cleanup remote directory
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            rm -rf ~/dcbot/app/node_modules
            rm -rf ~/dcbot/app/dist
            rm -rf ~/dcbot/app/.pnpm-store

      - name: Copy files to the server
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: './*'
          target: '/home/${{ secrets.SSH_USERNAME }}/dcbot/app'

      - name: Run container
        if: github.event_name == 'push' && github.ref_name == 'master'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/dcbot/app
            if [ "$(docker ps -aq -f name=discord-bot)" ]; then
              docker rm discord-bot --force
            fi
            # optionally remove the old image
            if [ "$(docker images -q discord-bot:latest)" ]; then
              docker rmi discord-bot:latest --force
            fi
            docker build -t discord-bot:latest .
            docker run -d --name discord-bot --env-file ../.env discord-bot
