name: Stop bot with cron or manually

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:


jobs:
  start:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: suspend ${{ secrets.FLY_APP }}




