name: Set the version

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

env:
  DC_TOKEN: ${{ secrets.DC_TOKEN }}
  DC_CLIENT_ID: ${{ secrets.DC_CLIENT_ID }}
  DC_GUILD_ID: ${{ secrets.DC_GUILD_ID }}
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.6

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"

      - name: Set version number in package.json
        run: |
          npm version $GITVERSION_SEMVER
      